app:
    resource: '@AppBundle/Controller/'
    type: annotation
app_blogpost:
    resource: "@AppBundle/Resources/config/routing/blogpost.yml"
    prefix:   /blogpost

app_blogcomment:
    resource: "@AppBundle/Resources/config/routing/blogcomment.yml"
    prefix:   /blogcomment
