blogpost_index:
    path:     /
    defaults: { _controller: "AppBundle:BlogPost:index" }
    methods:  GET

blogpost_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:BlogPost:show" }
    methods:  GET

blogpost_new:
    path:     /new
    defaults: { _controller: "AppBundle:BlogPost:new" }
    methods:  [GET, POST]

blogpost_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BlogPost:edit" }
    methods:  [GET, POST]

blogpost_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BlogPost:delete" }
    methods:  DELETE
